### ISSUE TITLE
Encapsular objetos do Cenario

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/Nave2#1]
A classe `JogoNave` cria três objetos (nave, inimigo e placar) para passar para o construtor do cenário.

Isso faz sentido no projeto original Nave 1.0 (que utiliza o BlueJ). Neste projeto, faria mais sentido que a própria classe `Cenario` criasse esses objetos.

**Comment by SergioHenrique19** [comment]
Boa noite, @caburu

Sou aluno da disciplina **Desenvolvimento de Software Livre** (GCC259). Gostaria de colaborar com o projeto através dessa issue.

**Comment by caburu** [comment]
Olá @SergioHenrique19, bom dia, bacana que está disposto a colaborar!

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviasse a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida quanto ao projeto ou à issue em si, estou à disposição.
